frameworkVersion: '3'

service: aws-node-http-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-${sls:stage}-customerTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-${sls:stage}-customerTable'

functions:
  hello:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get

  getAllCustomers:
    handler: customer-lambda/getAllCustomers.handler
    events:
      - httpApi:
          path: /
          method: get
  getCustomer:
    handler: customer-lambda/getCustomer.handler
    events:
      - httpApi:
          path: /{id}
          method: get
  createCustomer:
    handler: customer-lambda/createCustomer.handler
    events:
      - httpApi:
          path: /
          method: post

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-customerTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
