@url = https://sca4hegqkh.execute-api.us-east-1.amazonaws.com

###
GET {{url}}/hello

###
POST {{url}}
Content-Type: application/json

{
    "name": "Nir",
    "email": "Nir@example.com"
}

###
GET {{url}}/c3e05561-9c28-49e4-ad4e-ab06f0ce3099

###
GET {{url}}